/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Admin.java
 *
 * Created on Jul 15, 2015, 2:16:34 AM
 */

package exp;
//import swingjdbc.DatabaseConnect;
//import javax.swing.JFrame;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import java.sql.*;
import javax.swing.JOptionPane;
import swingjdbc.DatabaseConnect;

/**
 *
 * @author user
 */
public class Admin extends javax.swing.JFrame {

    public Admin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 900));
        setName("Form"); // NOI18N
        getContentPane().setLayout(null);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(exp.ExpApp.class).getContext().getResourceMap(Admin.class);
        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 50, 107, 34);

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 50, 110, 30);

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(30, 110, 150, 30);

        jTextField2.setText(resourceMap.getString("jTextField2.text")); // NOI18N
        jTextField2.setName("jTextField2"); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(220, 110, 150, 30);

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 180, 110, 40);

        jButton2.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 180, 120, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                  // Register Button
          String username=new String();
          String password=new String();
          username= jTextField1.getText();  // taking username from screen
          password= jTextField2.getText();  // taking password from screen

          try
          {
                        serial1=1;
			dc=new DatabaseConnect("Driver={Microsoft Access Driver (*.mdb)};DBQ=database.mdb;DriverID=22;READONLY=true","","");
                        rs= dc.searchDB("select * from p");
                        while(rs.next())
                        {
                            serial1++;
                        }
                        System.out.println(serial1);
                        rs.close();
                        rs= dc.searchDB("select ID from p where username='' and password='' ");
                        while(rs.next())
                          {
                            serial2++;
                             //dc.updateDB("Insert into db values('"+serial+"','"+username+"','"+password+"')");
                             //JOptionPane.showMessageDialog(frame, "Data inserted Scuccesfully");
                         // break;
                          }
                        rs.close();
                        int temp=0;
                        System.out.println(serial2);
                         if(serial2>1)
                        {
                            //System.out.println("if");
                            serial2=1;
                            rs= dc.searchDB("select ID from p where username='' and password='' ");
                            String s=new String();
                            while(rs.next())
                            {
                                s=rs.getString("ID");
                                temp=Integer.parseInt(s);
                                System.out.println(temp);
                            dc.updateDB("update p set username='"+username+"',password='"+password+"'where  ID="+s+"");

                            JOptionPane.showMessageDialog(frame, "Data inserted Scuccesfully");
                                break;
                            }
                            rs.close();

                        }
                         else{
                            //System.out.println("else");
                        dc.updateDB("Insert into p values('"+Integer.toString(serial1)+"','"+username+"','"+password+"')");

                        JOptionPane.showMessageDialog(frame, "Data inserted Scuccesfully");

                    }
          }
		catch(Exception e)
		{
			System.out.println (e);
		}
          try
          {
                        serial1j=1;
			dc=new DatabaseConnect("Driver={Microsoft Access Driver (*.mdb)};DBQ=database.mdb;DriverID=22;READONLY=true","","");
                        rs1= dc.searchDB("select * from j");
                        while(rs1.next())
                        {
                            serial1j++;
                        }
                        System.out.println(serial1j);
                        rs1.close();
                        rs1= dc.searchDB("select ID from j where username='' and password='' ");
                        while(rs1.next())
                          {
                            serial2j++;
                             //dc.updateDB("Insert into db values('"+serial+"','"+username+"','"+password+"')");
                             //JOptionPane.showMessageDialog(frame, "Data inserted Scuccesfully");
                         // break;
                          }
                        rs1.close();
                        int temp1=0;
                        System.out.println(serial2j);
                         if(serial2j>1)
                        {
                            //System.out.println("if");
                            serial2j=1;
                            rs1= dc.searchDB("select ID from j where username='' and password='' ");
                            String s1=new String();
                            while(rs1.next())
                            {
                                s1=rs1.getString("ID");
                                temp1=Integer.parseInt(s1);
                                System.out.println(temp1);
                            dc.updateDB("update j set username='"+username+"',password='"+password+"',name='',contact='',address='',email='' where  ID="+s1+"");

                            JOptionPane.showMessageDialog(frame, "Data inserted Scuccesfully");
                                break;
                            }
                            rs1.close();

                        }
                         else{
                            //System.out.println("else");
                        dc.updateDB("Insert into j values('"+Integer.toString(serial1j)+"','"+username+"','"+password+"','','','','')");

                        JOptionPane.showMessageDialog(frame, "Data inserted Scuccesfully");

                    }
          }
          catch(Exception e)
          {
              System.out.println (e);
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String username=new String();
        username= jTextField1.getText();   // TODO add your handling code here:
        try
		{
			dc=new DatabaseConnect("Driver={Microsoft Access Driver (*.mdb)};DBQ=database.mdb;DriverID=22;READONLY=true","","");
                        rs= dc.searchDB("select ID from p where username='"+username+"'");
                        while(rs.next())
                        {
                            serial1=Integer.parseInt(rs.getString("ID"));
                        }

                        System.out.println(serial1);
                        rs.close();
                        

                        //dc.updateDB("delete from p where username='"+username+"'");
                        //dc.updateDB("Insert into p values('"+Integer.toString(serial1)+"','','')");
                        dc.updateDB("update p SET username='',password='' where username='"+username+"'");
                        
                       // dc.updateDB("Insert into j values('"+Integer.toString(serial1j)+"','','','','','','')");

		}catch(Exception e)
		{
			System.out.println (e);
		}
        try
        {
            dc=new DatabaseConnect("Driver={Microsoft Access Driver (*.mdb)};DBQ=database.mdb;DriverID=22;READONLY=true","","");
                        rs1= dc.searchDB("select ID from j where username='"+username+"'");
                        while(rs1.next())
                        {
                            serial1j=Integer.parseInt(rs1.getString("ID"));
                        }

                        System.out.println(serial1j+"\ns2="+serial2+"\ns2="+serial2j);
                        rs1.close();
                        dc.updateDB("update j set username='',password='',name='',contact='',address='',email='' where username='"+username+"'");
        
        } catch (Exception e)
        {
            System.out.println (e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
  public DatabaseConnect dc;
  public static int serial1=1;
  public static int serial2=1;
  public static int serial1j=1;
  public static int serial2j=1;
  public JFrame frame;
      public Connection connection;
        public Statement stmt;
        public ResultSet rs;
        public ResultSet rs1;
}
