/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * rr.java
 *
 * Created on Jul 17, 2015, 2:20:38 PM
 */

package exp;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import java.sql.*;
import javax.swing.JOptionPane;
import swingjdbc.DatabaseConnect;
/**
 *
 * @author user
 */
public class rr extends javax.swing.JFrame {

    public rr() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(exp.ExpApp.class).getContext().getResourceMap(rr.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setMinimumSize(new java.awt.Dimension(900, 900));
        setName("Form"); // NOI18N
        getContentPane().setLayout(null);

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 60, 220, 30);

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 110, 22);

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 60, 100, 30);

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(550, 60, 80, 22);

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(10, 110, 130, 30);

        jTextField2.setText(resourceMap.getString("jTextField2.text")); // NOI18N
        jTextField2.setName("jTextField2"); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(170, 110, 180, 30);

        jTextField3.setText(resourceMap.getString("jTextField3.text")); // NOI18N
        jTextField3.setName("jTextField3"); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(380, 110, 130, 30);

        jTextField4.setText(resourceMap.getString("jTextField4.text")); // NOI18N
        jTextField4.setName("jTextField4"); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(520, 110, 120, 30);

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 220, 120, 31);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        String room=new String();
        String pass=new String();
        String ad=new String();
        String due=new String();
        String s=new String();
        String in=new String();
        int a=0;
        room=jTextField1.getText();
        pass=jTextField2.getText();
        ad=jTextField3.getText();
        due=jTextField4.getText();
        dc=new DatabaseConnect("Driver={Microsoft Access Driver (*.mdb)};DBQ=database.mdb;DriverID=22;READONLY=true","","");
        rs=dc.searchDB("select ID from hi where Room='"+room+"'");
        while(rs.next()){
            a=Integer.parseInt(rs.getString("ID"));
        }
        rs.close();
        rs= dc.searchDB("select Availability from hi where ID='"+a+"'");
        while(rs.next()){
        in=rs.getString("Availability");
        }
        rs.close();
        if(in.equals("Reserved"))
        {
            JOptionPane.showMessageDialog(frame, "The room is already reserved");
        }
        else
        {
            rs= dc.searchDB("select ID from hi where ID="+a+"");
            dc.updateDB("update hi SET Availability='"+"Reserved"+"' where ID="+a+"");
            rs.close();
            serial1=1;
            rs= dc.searchDB("select * from rr");
            while(rs.next())
            {
                serial1++;
            }
            System.out.println(serial1);
            rs.close();
            dc.updateDB("Insert into rr values('"+Integer.toString(serial1)+"','"+room+"','"+pass+"','"+ad+"','"+due+"')");
        }
        }catch(Exception e){
           System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
  public DatabaseConnect dc;
  public static int serial1=1;
  public static int serial2=1;
  public JFrame frame;
      public Connection connection;
        public Statement stmt;
        public ResultSet rs;
}
